import { NextRequest, NextResponse } from "next/server";
import { getSessionFromRequest, hashPassword } from "@/lib/auth";
import { connectDB } from "@/lib/db";
import { User } from "@/models/User";
import { Property } from "@/models/Property";
import { Transaction } from "@/models/Transaction";
import { Dataset } from "@/models/Dataset";
import { generateSecurePassword } from "@/lib/passwordGenerator";

/**
 * Super Admin: Get all users with dataset mappings and portfolio record counts
 * Uses O(1) aggregation pipelines to avoid N+1 database roundtrips
 */
export async function GET(req: NextRequest) {
  try {
    const session = await getSessionFromRequest(req);
    if (!session || session.role !== "super_admin") {
      return NextResponse.json(
        { success: false, error: "Unauthorized. Super Admin access required." },
        { status: 403 }
      );
    }

    await connectDB();

    const [users, datasets, propertyAgg, transactionAgg] = await Promise.all([
      User.find({}).sort({ createdAt: -1 }).lean(),
      Dataset.find({}).lean(),
      Property.aggregate([
        {
          $group: {
            _id: "$datasetId",
            count: { $sum: 1 },
          },
        },
      ]),
      Transaction.aggregate([
        {
          $group: {
            _id: "$datasetId",
            count: { $sum: 1 },
          },
        },
      ]),
    ]);

    const propCountMap = new Map<string, number>();
    for (const item of propertyAgg) {
      if (item._id) propCountMap.set(item._id, item.count);
    }

    const txCountMap = new Map<string, number>();
    for (const item of transactionAgg) {
      if (item._id) txCountMap.set(item._id, item.count);
    }

    // Enrich users in memory with zero extra DB roundtrips
    const enrichedUsers = users.map((u) => {
      const dId = u.datasetId || `ds_${u._id.toString()}`;
      const propertyCount = propCountMap.get(dId) || 0;
      const transactionCount = txCountMap.get(dId) || 0;

      return {
        id: u._id.toString(),
        name: u.name,
        email: u.email,
        role: u.role,
        datasetId: dId,
        status: u.status || "active",
        propertyCount,
        transactionCount,
        createdAt: u.createdAt,
      };
    });

    return NextResponse.json({
      success: true,
      data: {
        users: enrichedUsers,
        datasets: datasets.map((d) => ({
          datasetId: d.datasetId,
          name: d.name,
          description: d.description,
        })),
      },
    });
  } catch (error: unknown) {
    const errorMsg =
      error instanceof Error ? error.message : "Failed to load admin controls";
    return NextResponse.json(
      { success: false, error: errorMsg },
      { status: 500 }
    );
  }
}

/**
 * Super Admin: Create a new user with optional 15-char autogenerated password and dataset mapping
 */
export async function POST(req: NextRequest) {
  try {
    const session = await getSessionFromRequest(req);
    if (!session || session.role !== "super_admin") {
      return NextResponse.json(
        { success: false, error: "Unauthorized. Super Admin access required." },
        { status: 403 }
      );
    }

    const { name, email, password, role, datasetId, autoGeneratePassword } =
      await req.json();

    if (!name || !email) {
      return NextResponse.json(
        { success: false, error: "Name and email are required" },
        { status: 400 }
      );
    }

    const normalizedEmail = email.toLowerCase().trim();

    await connectDB();
    const existing = await User.findOne({ email: normalizedEmail });
    if (existing) {
      return NextResponse.json(
        { success: false, error: "A user with this email already exists" },
        { status: 409 }
      );
    }

    // Determine password: generate strict 15-char secure password if requested or omitted
    const plainPassword =
      autoGeneratePassword || !password
        ? generateSecurePassword(15)
        : password.trim();

    const pHash = await hashPassword(plainPassword);
    const assignedDatasetId =
      datasetId && datasetId.trim() !== ""
        ? datasetId.trim()
        : `ds_${normalizedEmail.replace(/[^a-zA-Z0-9]/g, "_")}`;

    const newUser = await User.create({
      name: name.trim(),
      email: normalizedEmail,
      passwordHash: pHash,
      role: role || "user",
      datasetId: assignedDatasetId,
      status: "active",
    });

    // Ensure dataset record exists
    await Dataset.findOneAndUpdate(
      { datasetId: assignedDatasetId },
      {
        $setOnInsert: {
          datasetId: assignedDatasetId,
          name: `${name.trim()}'s Portfolio`,
          description: `Dedicated portfolio workspace for ${normalizedEmail}`,
        },
        $addToSet: { assignedUserIds: newUser._id.toString() },
      },
      { upsert: true, new: true }
    );

    return NextResponse.json({
      success: true,
      data: {
        id: newUser._id.toString(),
        name: newUser.name,
        email: newUser.email,
        role: newUser.role,
        datasetId: newUser.datasetId,
        generatedPassword: plainPassword,
      },
    });
  } catch (error: unknown) {
    const errorMsg =
      error instanceof Error ? error.message : "Failed to create user";
    return NextResponse.json(
      { success: false, error: errorMsg },
      { status: 500 }
    );
  }
}

/**
 * Super Admin: Update user role, mapped dataset, status, or reset password
 */
export async function PUT(req: NextRequest) {
  try {
    const session = await getSessionFromRequest(req);
    if (!session || session.role !== "super_admin") {
      return NextResponse.json(
        { success: false, error: "Unauthorized. Super Admin access required." },
        { status: 403 }
      );
    }

    const { userId, name, role, datasetId, status, resetPassword } =
      await req.json();

    if (!userId) {
      return NextResponse.json(
        { success: false, error: "userId is required" },
        { status: 400 }
      );
    }

    await connectDB();
    const userToUpdate = await User.findById(userId);
    if (!userToUpdate) {
      return NextResponse.json(
        { success: false, error: "User not found" },
        { status: 404 }
      );
    }

    let generatedNewPassword = "";
    if (resetPassword) {
      generatedNewPassword = generateSecurePassword(15);
      userToUpdate.passwordHash = await hashPassword(generatedNewPassword);
    }

    if (name) userToUpdate.name = name.trim();
    if (role) userToUpdate.role = role;
    if (datasetId) userToUpdate.datasetId = datasetId.trim();
    if (status) userToUpdate.status = status;

    await userToUpdate.save();

    return NextResponse.json({
      success: true,
      data: {
        id: userToUpdate._id.toString(),
        name: userToUpdate.name,
        email: userToUpdate.email,
        role: userToUpdate.role,
        datasetId: userToUpdate.datasetId,
        status: userToUpdate.status,
        generatedPassword: generatedNewPassword || undefined,
      },
    });
  } catch (error: unknown) {
    const errorMsg =
      error instanceof Error ? error.message : "Failed to update user";
    return NextResponse.json(
      { success: false, error: errorMsg },
      { status: 500 }
    );
  }
}

/**
 * Super Admin: Delete user account
 */
export async function DELETE(req: NextRequest) {
  try {
    const session = await getSessionFromRequest(req);
    if (!session || session.role !== "super_admin") {
      return NextResponse.json(
        { success: false, error: "Unauthorized. Super Admin access required." },
        { status: 403 }
      );
    }

    const { searchParams } = new URL(req.url);
    const userId = searchParams.get("userId");

    if (!userId) {
      return NextResponse.json(
        { success: false, error: "userId query param required" },
        { status: 400 }
      );
    }

    if (userId === session.userId) {
      return NextResponse.json(
        { success: false, error: "Cannot delete your own super admin account" },
        { status: 400 }
      );
    }

    await connectDB();
    await User.findByIdAndDelete(userId);

    return NextResponse.json({ success: true, message: "User deleted successfully" });
  } catch (error: unknown) {
    const errorMsg =
      error instanceof Error ? error.message : "Failed to delete user";
    return NextResponse.json(
      { success: false, error: errorMsg },
      { status: 500 }
    );
  }
}
